<a href="https://colab.research.google.com/github/Santigs/AI/blob/master/Deeplizard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep learning exercise from DeepLizard [Videocourse](https://www.youtube.com/watch?v=UkzhouEk6uY&list=PLZbbT5o_s2xrwRnXk_yCPtnqqo4_u2YGL&index=3)

---






### Creating a random set of sample data

In [0]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [0]:
train_labels = []
train_samples = []

In [0]:
for i in range(50):
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)




In [0]:
for i in train_samples:
  print(i)
  

In [0]:
for i in train_labels:
  print(i)

In [0]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)

In [62]:
train_samples

array([34, 94, 32, ..., 70, 50, 93])

In [63]:
train_labels

array([1, 0, 1, ..., 1, 0, 1])

In [0]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform((train_samples).reshape(-1,1))


In [65]:
scaled_train_samples

array([[0.24137931],
       [0.93103448],
       [0.2183908 ],
       ...,
       [0.65517241],
       [0.42528736],
       [0.91954023]])

In [0]:
for i in scaled_train_samples:
  print(i)


### Defining the Model Neural Network Architecture

In [10]:
%tensorflow_version 1.x
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

Using TensorFlow backend.


In [0]:
model = Sequential([
                    Dense(16, input_shape=(1,), activation='relu' ),
                    Dense(32, activation='relu'),
                    Dense(2, activation='softmax')
])

In [67]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_8 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


### Training the Model

In [0]:
model.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [69]:
# make sure the validation set (which is the % at the end of the sample set) is representative of the whole population
model.fit(scaled_train_samples, train_labels, validation_split=0.1   , batch_size=10, epochs=20, shuffle=True, verbose=2)

Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 1s - loss: 0.6434 - acc: 0.5413 - val_loss: 0.6246 - val_acc: 0.6048
Epoch 2/20
 - 0s - loss: 0.6260 - acc: 0.6132 - val_loss: 0.6029 - val_acc: 0.6667
Epoch 3/20
 - 0s - loss: 0.6025 - acc: 0.6910 - val_loss: 0.5728 - val_acc: 0.7333
Epoch 4/20
 - 0s - loss: 0.5784 - acc: 0.7365 - val_loss: 0.5446 - val_acc: 0.7762
Epoch 5/20
 - 0s - loss: 0.5538 - acc: 0.7683 - val_loss: 0.5149 - val_acc: 0.8190
Epoch 6/20
 - 0s - loss: 0.5282 - acc: 0.7942 - val_loss: 0.4846 - val_acc: 0.8524
Epoch 7/20
 - 0s - loss: 0.5025 - acc: 0.8201 - val_loss: 0.4541 - val_acc: 0.8762
Epoch 8/20
 - 0s - loss: 0.4775 - acc: 0.8407 - val_loss: 0.4243 - val_acc: 0.8952
Epoch 9/20
 - 0s - loss: 0.4539 - acc: 0.8545 - val_loss: 0.3959 - val_acc: 0.9000
Epoch 10/20
 - 0s - loss: 0.4320 - acc: 0.8635 - val_loss: 0.3703 - val_acc: 0.9238
Epoch 11/20
 - 0s - loss: 0.4120 - acc: 0.8720 - val_loss: 0.3464 - val_acc: 0.9333
Epoch 12/20
 - 0s - loss: 0.3942 - acc

### Preprocess Test data

In [0]:
test_labels = []
test_samples = []

In [0]:
for i in range(10):
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(1)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_labels.append(0)

for i in range(200):
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(0)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_labels.append(1)

In [0]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

In [0]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1,1))

### Predict

In [0]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)

In [77]:
for i in predictions:
  print(i)


[0.8999375  0.10006255]
[0.13296556 0.8670345 ]
[0.5174817  0.48251835]
[0.31786686 0.68213314]
[0.8985566 0.1014434]
[0.22676408 0.77323586]
[0.8981206 0.1018794]
[0.14401047 0.8559895 ]
[0.898991   0.10100903]
[0.33827835 0.66172165]
[0.8976829  0.10231705]
[0.05021411 0.9497859 ]
[0.7651908  0.23480926]
[0.16838181 0.83161825]
[0.7968278  0.20317222]
[0.4254328  0.57456726]
[0.6515033  0.34849674]
[0.19593349 0.80406654]
[0.89470285 0.10529716]
[0.27912125 0.7208788 ]
[0.67222595 0.3277741 ]
[0.14401047 0.8559895 ]
[0.898991   0.10100903]
[0.03732953 0.96267045]
[0.63019115 0.36980882]
[0.35931015 0.64068985]
[0.8976829  0.10231705]
[0.03523966 0.9647603 ]
[0.47121248 0.5287875 ]
[0.04706881 0.9529312 ]
[0.8985773  0.10142276]
[0.14401047 0.8559895 ]
[0.8998548  0.10014528]
[0.09577519 0.90422475]
[0.7651908  0.23480926]
[0.13296556 0.8670345 ]
[0.8905744  0.10942557]
[0.05814904 0.94185096]
[0.8905744  0.10942557]
[0.1226464 0.8773536]
[0.8998145  0.10018552]
[0.03732953 0.96267045

In [0]:
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)


In [79]:
for i in rounded_predictions:
  print(i)

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
